### ISSUE TITLE
エディタ利用時に気になる挙動のリスト

### ISSUE THREAD

**Issue by y-temp4** [AlisProject/alis-editor-old#20]
### すぐに実装で対応できるもの

- [x] 1 つ目のブロックだけで Block の append がうまくいかないことがある
- [x] 本文の途中でエンターを押すたびに「Type here...」が増え続ける
- [x] 本文の最後にカーソルがある状態でエンターを押すと次の行が表示されるがカーソルが移動しない
- [x] 本文の最初にURLを貼り付けるとURLごとその下の本文も消える
- [x] 画像の Align  / Caption 対応
- [ ] 埋め込みの発火をペーストからペースト→Enterにする

### 古いコミットログからのサルベージ + αで解決するもの

- [x] 引用部分が編集時にすべて表示されない（途切れる）

### 相応の工数を要するもの

- [ ] カーソルが上下移動しない
- [x] 本文を選択しても装飾項目が表示されない
  - フローティングにしない場合は早期で解決可能。フローティングの場合はすぐにはできない。

**Comment by potato4d** [comment]
大体直せそうですが、「カーソルが上下移動しない」についてはモバイル版の実装にあたって一旦復旧させたコードを戻してきても、実質工数としてそれだけで半日以上掛かりそうな気がします。

ステージング立ち上げてしまって、修正していく作業の中で対応かなぁと思います。

**Comment by potato4d** [comment]
- [ ] １つ目のブロックだけで Block の append がうまくいかないことがある

**Comment by potato4d** [comment]
ちょっと Issue の本文を修正して、挙動を以下にわけます。

- 古いコミットログから復旧したらすぐに解決できるもの
- 古いコミットログから復旧しても難しいもの(モバイルとなった以降はモバイルを前提としたスケジュール感になっているため、その工数では PC では難しいもの)
- 簡単なバグ

**Comment by y-temp4** [comment]
挙動の本文の修正ありがとうございます🙏

**Comment by y-temp4** [comment]
@potato4d 
「条件が不十分なので詳細をもらいたいもの」の
`本文中にカーソルがある状態でエンターを押しても次の行に移動しないことがある` は、「すぐに実装で対応できるもの」のエンターを押したときの挙動に関連した動作っぽいので消しました。

また、 `本文の途中にURLを貼り付けてもOGP展開されないことがある（URLが消える）`  を `本文の最初にURLを貼り付けるとURLごとその下の本文も消える` に修正しました！

**Comment by potato4d** [comment]
この間もちらっと話してましたが、フローティングメニューに関しては bold 化以外はあんまり現実的じゃなさそうな感じがしました。

**Comment by potato4d** [comment]
note.mu の挙動と同じなら問題なくできそう

**Comment by potato4d** [comment]
[![Image from Gyazo](https://i.gyazo.com/ee656663b2c2696de2fb13da3fd85910.gif)](https://gyazo.com/ee656663b2c2696de2fb13da3fd85910)
できてしまった
